CPPFLAGS=
LGFLAGS=  -lsfml-graphics -lsfml-window -lsfml-system -o handlarz

handlarz: main.o openall.o gra.o guzik.o menu.o garden.o guzikwarz.o shop.o guziksklep.o cave.o orchard.o hodowla.o timerbar.o 
	g++ main.o openall.o gra.o guzik.o menu.o garden.o guzikwarz.o shop.o guziksklep.o cave.o orchard.o hodowla.o timerbar.o -o handlarz -lsfml-graphics -lsfml-window -lsfml-system